name: Publish to crates.io

on:
  push:
    branches:
      - main
    paths:
      - 'cli/**'

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('cli/Cargo.lock') }}
          
      - name: Build and test
        run: |
          cd cli
          cargo build --release
          cargo test
          
      - name: Publish to crates.io
        run: |
          cd cli
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
